
- hosts: localhost
  vars:
    ansible_connection: local
    ansible_python_interpreter: /usr/bin/python3

  tasks:

    - package:
        name:
#         - yq
        - python3-pip
        state: present
        
        

    - pip:
        name:
        - docker
        state: present



