- hosts: localhost
  vars:
    ansible_connection: local
    ansible_python_interpreter: /usr/bin/python3

  tasks:

    - mail:
        host: localhost
        port: 25
        to: S.Koulouzis@uva.nl
        subject: Ansible-report
        body: System {{ ansible_hostname }} has been successfully provisioned.
        secure: starttls

