- hosts: localhost
  vars:
    ansible_connection: local
    ansible_python_interpreter: /usr/bin/python3

  tasks:

    - mail:
        host: smtp.gmail.com
        port: 587
        username: "{{user_name}}"
        password: "{{password}}"
        to: "{{send_to}}"
        subject: Ansible-report
        body: "{{body}}"

