---
- hosts: localhost
  vars:
    ansible_connection: local
    ansible_python_interpreter: /usr/bin/python3

  tasks:

    - debug:
        var: id

    - name: delete
      uri:
        validate_certs: no
        timeout: 2400
        url: "{{baseUrl}}/tosca_template/{{id}}"
        method: DELETE
        headers:
          accept: "text/plain"
        user: "{{ sdia_user }}"
        password: "{{ sdia_password }}"
        force_basic_auth: yes
        status_code: 200
      ignore_errors: yes
        

    - wait_for:
        host: "{{item}}"
        port: 22
        state: started
        timeout: 30
      with_items:
        - "{{ topology_template['node_templates']['compute']['attributes']['public_ip']}}"
        - "{{ topology_template['node_templates']['compute_1']['attributes']['public_ip']}}"
      register: ssh_connection
      ignore_errors: yes

    - set_stats:
        data:
          body: "VMs, are still running. {{item}}"
      when: not item['failed']
      loop: "{{ssh_connection['results']}}"
      
        
    - name: check if vms are deleted
      fail:
        msg: VMs are still running
      when: not item['failed']
      loop: "{{ssh_connection['results']}}"
     









