---
- hosts: localhost
  vars:
    ansible_connection: local
    ansible_python_interpreter: /usr/bin/python3

  tasks:

    - docker_image:
        name: "{{image_name}}"
        source: pull

    - docker_image_info:
        name: "{{image_name}}"
      register: docker_image_info

    - debug:
        var: docker_image_info