
- hosts: localhost
  vars:
    ansible_connection: local
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name:  check the tosca template that will be used
      uri:
        validate_certs: no
        url: "{{baseUrl}}/tosca_template/{{tosca_id}}"
        method: GET
        headers:
          accept: "text/plain"
        user: "{{ sdia_user }}"
        password: "{{ sdia_password }}"
        force_basic_auth: yes
        status_code: 200

    - name: check file
      get_url:
        validate_certs: no
        url: "{{baseUrl}}/tosca_template/{{tosca_id}}"
        headers:
          accept: "text/plain"
        url_username: "{{ sdia_user }}"
        url_password: "{{ sdia_password }}"
        force_basic_auth: yes
        force: yes
        dest: /tmp/tosca_tmp.yaml

    - include_vars:
        file: /tmp/tosca_tmp.yaml
        name: tosca

    - name: provision
      get_url:
        validate_certs: no
        url: "{{baseUrl}}/provisioner/provision/{{tosca_id}}"
        headers:
          accept: "text/plain"
        url_username: "{{ sdia_user }}"
        url_password: "{{ sdia_password }}"
        force_basic_auth: yes
        force: yes
        dest: /tmp/provision_id


    - include_vars:
        file: /tmp/provision_id
        name: provision_id

    - debug:
        var: provision_id


