---
- hosts: localhost
  vars:
    ansible_connection: local
    ansible_python_interpreter: /usr/bin/python3

  tasks:


#     - name: delete
#       uri:
#         validate_certs: no
#         url: "{{baseUrl}}/tosca_template/{{id}}"
#         method: DELETE
#         headers:
#           accept: "text/plain"
#         user: "{{ sdia_user }}"
#         password: "{{ sdia_password }}"
#         force_basic_auth: yes
#         status_code: 200

    - wait_for:
        host: "{{item}}"
        port: 22
        state: started
      with_items:
        - "{{ provisioned['topology_template']['node_templates']['compute']['attributes']['public_ip']}}"
        - "{{ provisioned['topology_template']['node_templates']['compute_1']['attributes']['public_ip']}}"
      register: ssh_connection
      ignore_errors: yes


    - debug:
        var: ssh_connection

#    - name: check if vms are deleted
#      fail:
#        msg: VMs are still running
#      when: cmdb_status != "to-be-staged"









