---
- hosts: localhost
  vars:
    ansible_connection: local
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - set_fact:
        random_name: "sdia_{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=8') }}"

    - set_stats:
        data:
          random_name: "{{random_name}}"
          
    - name: Create tosca directory if it does not exist
      file:
        path: /tmp/tosca
        state: directory
        
        
    - find:
        paths: /tmp/tosca/
        patterns: "*"
        age: 3d
      register: older_files
      
          
    - name: Download
      get_url:
        timeout: 2400
        validate_certs: no
        url: "{{tosca_url}}"
        headers:
          accept: "text/plain"
        force: yes
        dest: /tmp/tosca/tosca_{{random_name}}.yaml
      register: get_url_output
      
      
    - debug:
        var: get_url_output
      
    - name:  upload tosca
      shell: curl -k -u {{ sdia_user }}:{{ sdia_password }} --location --request POST {{baseUrl}}/tosca_template -F file=@/tmp/tosca/tosca_{{random_name}}.yaml
      register: uri_output
      
    - debug:
        var: uri_output
     

    - set_stats:
        data:
          tosca_id: "{{uri_output.stdout}}"
          sdia_user: "{{sdia_user}}"
          sdia_password: "{{sdia_password}}"
